feat: password dictionary to exclude common password
gravitee-io/gravitee-access-management pull request #1456
Opened 2021-11-17 15:10 UTC by remisultan

closes: [issue/6520](https://github.com/gravitee-io/issues/issues/6520)

This issues introduces a password dictionary so common unsafe password are excluded.

- Activate the feature at domain level or client (application) level
<img width="1775" alt="Screenshot 2021-11-17 at 14 19 10" src="https://user-images.githubusercontent.com/8531515/142223823-0ce32020-c6fb-4585-9697-f126579f4047.png">
<img width="1775" alt="Screenshot 2021-11-17 at 14 19 10" src="https://user-images.githubusercontent.com/8531515/142224020-8af067c1-103e-41a4-aa8d-692dfa92e98e.png">

You can test the feature within 3 contexts:
1. Creating a new user in the AM console UI (only at domain level)
First case: create the user and try to input a password excluded from the list. You should receive an error if not correct, otherwise the user gets registered
<img width="1783" alt="Screenshot 2021-11-17 at 15 43 13" src="https://user-images.githubusercontent.com/8531515/142224575-8565cb40-b1a8-4777-9421-006175d4641a.png">
Second case: Create the user and click on `Enable Pre-registration`, go to the users inbox and click the link to confirm signup. Try to enter a password excluded from the list.

<img width="1475" alt="Screenshot 2021-11-17 at 15 51 03" src="https://user-images.githubusercontent.com/8531515/142224871-35c3317a-3ecb-4180-972b-f3049e85e757.png">

2. Register the user via the login flow

Make sure these are selected first
<img width="1785" alt="Screenshot 2021-11-17 at 15 46 02" src="https://user-images.githubusercontent.com/8531515/142226319-a1c01d28-6c96-44a1-8727-618e61ca83a7.png">
<img width="1777" alt="Screenshot 2021-11-17 at 15 46 14" src="https://user-images.githubusercontent.com/8531515/142226336-4f829961-d00b-4cab-aaba-a682778aefef.png">

Initiate the login flow and click on `No account ? Register`
Try to input the user's info and an excluded password.

<img width="1713" alt="Screenshot 2021-11-17 at 15 48 57" src="https://user-images.githubusercontent.com/8531515/142226531-1b0e093c-1766-4ddc-ac38-19b0f161237f.png">

3. Reset password 
Initiate the login flow and click on `Forgot Password ?` and input the email. Get to the inbox, click on the resetPassword link and try to input an excluded password.

4. Reset password via the SelfAccount Management API
Login with the `cloud-app` (make sure  SelfAccount Management API is enabled) and try to input a wrong password within the account section.

Technical:

Go to management API and try to target a dictionary file

```yml
      dictionary:
         filename: /path/to/dictionary  # if null `resources/dictionaries/10k-most-common.txt` will be loaded
         watch: true #if true, watches periodically for any changes in the file
```

When changing its content, if watching the file, the dictionary should be updated (check the logs)

2021-11-18 08:05 UTC, remisultan commented on gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EntrypointServiceImpl.java
> +                        if (!VirtualHostValidatorImpl.isValidDomainOrSubDomain(hostWithoutPort, organization.getDomainRestrictions())) {
use virtualHostValidator bean

2021-12-02 21:09 UTC, tcompiegne requested changes

2021-12-02 21:09 UTC, tcompiegne commented on gravitee-am-password-dictionary/src/main/java/io/gravitee/am/password/dictionary/spring/PasswordDictionaryConfiguration.java
> +    @Value("#{graviteeProperties['user.password.policy.dictionary.filename']}")
Use instead `@Value("${user.password.policy.dictionary.filename:#{null}}")` to be able to set filename like :  `${gravitee.home}/dictionary/10k-most-common.txt`

2021-12-03 08:27 UTC, tcompiegne requested changes

2021-12-03 08:27 UTC, tcompiegne commented on gravitee-am-password-dictionary/src/main/java/io/gravitee/am/password/dictionary/spring/PasswordDictionaryConfiguration.java
> +    @Value("#{T(java.lang.Boolean).TRUE.equals(graviteeProperties['user.password.policy.dictionary.watch'])}")
graviteeProperties do not resolve environment variable, usse`${user.password.policy.dictionary.watch:false}` instead.

2021-12-03 10:41 UTC, merged