feat: user profile pattern password validation
gravitee-io/gravitee-access-management pull request #1459
Opened 2021-11-19 14:05 UTC by remisultan

This feature allows to exclude user profile information within the password (case insensitive)

The testing process is the same as this one: https://github.com/gravitee-io/gravitee-access-management/pull/1456
Instead: Toggle `Exclude user profile information in password` in the Password Policy Settings

2021-12-03 14:11 UTC, tcompiegne requested changes

2021-12-03 14:11 UTC, tcompiegne commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/PasswordPolicyRequestParseHandler.java
> +        User user = context.get(MODEL_USER_KEY);
We have already a key for that : `ConstantKeys.USER_CONTEXT_KEY`

2021-12-03 14:11 UTC, tcompiegne commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserRequestHandler.java
> +        io.gravitee.am.model.User user = routingContext.get(MODEL_USER_KEY);
Use `ConstantKeys.USER_CONTEXT_KEY` instead.

2021-12-03 14:58 UTC, remisultan commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserRequestHandler.java
> +        io.gravitee.am.model.User user = routingContext.get(MODEL_USER_KEY);
FP

2021-12-20 10:48 UTC, tcompiegne approved these changes

2021-12-20 10:48 UTC, merged