fix: Plugin initializers onActivate onDeactivate
gravitee-io/gravitee-access-management pull request #1599
Opened 2022-01-14 16:51 UTC by remisultan

fixes https://github.com/gravitee-io/issues/issues/6942

2022-01-14 16:52 UTC, remisultan commented
Still need to discuss this while this is in draft.
@tcompiegne @leleueri

2022-01-20 09:55 UTC, leleueri requested changes

2022-01-20 09:55 UTC, leleueri commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> +groovy:
should it be part of the commit ?

2022-01-20 09:55 UTC, leleueri commented on gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
> +groovy:
should it be part of the commit ?

2022-01-21 16:25 UTC, remisultan commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> +groovy:
good call

2022-01-21 16:26 UTC, remisultan commented on gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
> +groovy:
good call

2022-02-09 21:37 UTC, tcompiegne approved these changes

2022-02-09 21:38 UTC, merged