fix: define hidden field to provide state parameter when the Identity…
gravitee-io/gravitee-access-management pull request #1616
Opened 2022-01-20 11:23 UTC by leleueri

…FirstLogin form is submitted.

Also add the minimal template example for IDENTIFIER_FIRST_LOGIN

fixes gravitee-io/issues#6975

2022-01-20 20:22 UTC, tcompiegne requested changes
I'm not sure about this solution, maybe we have to rewrite this flow more deeply : 

- GET /identifier-first
- POST /identifier-first
  - Redirect to matching IdP
  - or redirect to AM login page

2022-01-23 20:43 UTC, tcompiegne requested changes
PR has been force pushed to rewrite the Identifier-first login flow.

Waiting for a new review.

2022-01-27 17:18 UTC, remisultan requested changes
Usage is fine

A few minor comments on code

Postman test are breaking:
![image](https://user-images.githubusercontent.com/8531515/151410077-4191ddc1-7b29-4e8c-9fa9-78789cc6d877.png)

2022-01-27 20:20 UTC, tcompiegne commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpoint.java
> +
We do the check just after

```
 final IdentityProvider identityProvider = socialProviders
                .stream()
                .filter(s -> s.getDomainWhitelist() != null && s.getDomainWhitelist().stream().anyMatch(domainName[1]::equals))
                .findFirst()
                .orElse(null);

        // no IdP has matched, continue
        if (identityProvider == null) {
            doInternalRedirect(routingContext);
            return;
        }
```

2022-01-27 21:02 UTC, tcompiegne commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpointHandlerTest.java
> +                    //assertEquals(routingContext.get(BACK_TO_LOGIN_IDENTIFIER_ACTION_KEY), resolveProxyRequest(routingContext.request(), routingContext.get(CONTEXT_PATH) + "/login/identifier", query
FP

2022-01-28 13:10 UTC, remisultan commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpoint.java
> +
👍

2022-01-28 13:11 UTC, remisultan approved these changes
LGTM

2022-01-28 13:36 UTC, merged