test: cypress setup and add login ui test
gravitee-io/gravitee-access-management pull request #1666
Opened 2022-02-09 14:57 UTC by patelami

This branch includes
1. Cypress setup 
2. Login ui test

2022-02-11 14:03 UTC, ctschacher commented on gravitee-am-cypress/cypress/integration/login-ui-test.ts
> +    cy.get(loginFormTitle).contains("Sign In");
It's not wrong but just a hint if you test the same element again you can also use 'and' to combine them:
`cy.get(loginFormTitle).should("be.visible").and('contain', 'Sign In');`
 The result is the same as Cypress will perform two separate tests it's maybe just more readable.

2022-02-11 14:08 UTC, ctschacher commented on gravitee-am-cypress/cypress/integration/login-ui-test.ts
> +    cy.get(password).type("adminadmin");
In APIM we have users defined as environment variables in cypress.json, could be an option here as well.

2022-02-11 14:21 UTC, ctschacher commented on gravitee-am-cypress/cypress/tsconfig.json
> +    "lib": ["es5", "dom"],
ES5 is quite outdated, ES2020 is maybe more appropriate.

2022-02-11 14:24 UTC, ctschacher commented on gravitee-am-cypress/package.json
> +        "test:parallel": "cypress run --record --group apis --spec 'cypress/integration/rest-api/apis/**/*' --config-file cypress/integration/rest-api/cypress-config.json",
The files and folders for these commands don't exist (yet?), so they won't work.

2022-02-11 19:17 UTC, leleueri commented on .gitignore
> +gravitee-apim-cypress/cypress/screenshots/
I think you mean gravitee-am-cypress :)

2022-02-15 08:30 UTC, leleueri requested changes

2022-02-15 08:30 UTC, leleueri commented on gravitee-am-cypress/cypress.json
> +  "baseUrl": "http://localhost/am/ui",
Is it possible to move the baseUrl into env section?
Will be probably more flexible and allow us to run easily the tests on multiple platform.

2022-02-15 20:09 UTC, leleueri requested changes
LGTM but circleci fails due to license header issue.

2022-02-17 11:53 UTC, merged