feat: provide the sourceId in to user entity
gravitee-io/gravitee-access-management pull request #1695
Opened 2022-02-23 11:09 UTC by leleueri

fixes gravitee-io/issues#7108

2022-02-23 15:08 UTC, leleueri commented
wrong origin branch

2022-02-24 12:50 UTC, remisultan approved these changes
LGTM

2022-03-31 14:40 UTC, farmborough approved these changes
LGTM.

2022-03-31 21:14 UTC, tcompiegne requested changes

2022-04-01 14:58 UTC, tcompiegne approved these changes

2022-04-01 14:59 UTC, merged