feat: conditional policies on flow steps
gravitee-io/gravitee-access-management pull request #1711
Opened 2022-03-08 22:35 UTC by remisultan

closes: https://github.com/gravitee-io/issues/issues/7015

## How to Test

1. Create a Policy flow (either at domain or application level) to allow a validation of Conditional policy (see below)

![Screenshot 2022-03-08 at 22 05 07](https://user-images.githubusercontent.com/8531515/157337219-b8b1e751-088f-4f26-b61b-5043d646a1dd.png)
![Screenshot 2022-03-08 at 22 05 15](https://user-images.githubusercontent.com/8531515/157337227-a0433440-ee56-417e-a9a6-0ab0565e2691.png)
![Screenshot 2022-03-08 at 22 05 28](https://user-images.githubusercontent.com/8531515/157337281-7993ac51-1deb-4c30-9801-1164551039db.png)

Reverse the condition in the condition of the step to be able to assert the use

2022-03-10 15:13 UTC, leleueri requested changes

2022-03-10 15:15 UTC, leleueri commented
When I want to update an existing EL into the condition fields, the changed are applied on the search text field after enter a space (probably more related to the UI component part) :

![image](https://user-images.githubusercontent.com/3110552/157692304-4d02dedc-6f61-4e5c-8baa-55279ee98d1f.png)

2022-03-10 15:48 UTC, remisultan commented on gravitee-am-gateway/gravitee-am-gateway-policy/src/main/java/io/gravitee/am/gateway/policy/impl/PolicyChain.java
> +            LOGGER.error("Could not execute rule [{}] for policy [{}]", condition, policy.id(), e);
I agree

2022-03-10 15:54 UTC, remisultan commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/execution/ExecutionPolicy.java
> +    private final Policy policy;
That file is useless

2022-03-11 15:18 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/flow/FlowManagerTest.java
> +        verify(policyPluginManager, never()).create(anyString(), eq(null), anyString());
Might as well use `isNull()`.

2022-03-11 15:32 UTC, farmborough approved these changes

2022-03-11 15:32 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/PolicyChainHandlerTest.java
> +        verify(flowManager, times(1)).findByExtensionPoint(eq(ExtensionPoint.PRE_CONSENT), eq(null), any(ExecutionPredicate.class));
`isNull()`?

2022-03-12 11:58 UTC, tcompiegne approved these changes

2022-03-12 11:58 UTC, tcompiegne commented
Well done @remisultan 👍

2022-03-12 11:59 UTC, merged