ci: secrethub to keeper
gravitee-io/gravitee-access-management pull request #1750
Opened 2022-03-25 14:34 UTC by Hakim187

This PR is created in purpose of migrating the secrets retrieving from the keeper CLI as secrethub will be soon migrated to 1password secrets management, and it will be non opertational at **1st of April**

New keeper orb is developped, and it works the same way as the secrethub orb, so the changes in this PR are mostly replacement of secrethub with keeper

Keeper orb link : https://github.com/gravitee-io/keeper-circleci-orb/tree/v0.5.0

CCI Pipeline link : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-access-management/5659/workflows/47381d0d-e250-4494-b91b-739539af2b9c

2022-03-28 07:01 UTC, leleueri commented
linked to gravitee-io/issues#7380

2022-03-28 07:38 UTC, leleueri requested changes
We still have the` gravitee/d_pull_requests_secrets` that depend on the secrethub system.

2022-03-28 08:19 UTC, Hakim187 commented
@leleueri yes that's one of the jobs in the gravitee orb, this orb will also move to keeper this week, and the name of all secret jobs inside will remain the same, just the content

2022-03-29 09:58 UTC, leleueri approved these changes

2022-03-29 09:58 UTC, merged