chore: create gatling simulation for audit log and user search
gravitee-io/gravitee-access-management pull request #1757
Opened 2022-03-29 08:10 UTC by ashraf706

2022-03-29 15:29 UTC, leleueri requested changes

2022-03-30 08:53 UTC, ashraf706 commented on gravitee-am-performance/src/test/scala/io/gravitee/am/performance/search/SearchUser.scala
> +  def getSearchString(index: Int) = {
readable, did some scala around 2013 :) , updated as suggested. Thanks

2022-03-30 08:54 UTC, ashraf706 commented on gravitee-am-performance/src/test/scala/io/gravitee/am/performance/search/SearchAuditLog.scala
> +  def createSearchFeeder() = {
updated as suggested.

2022-04-01 08:40 UTC, leleueri approved these changes

2022-04-01 08:40 UTC, merged