feat: support ECDSA JWT signing.
gravitee-io/gravitee-access-management pull request #1761
Opened 2022-03-30 20:35 UTC by farmborough

fixes gravitee-io/issues#4059

2022-04-05 07:25 UTC, leleueri requested changes

2022-04-05 07:25 UTC, leleueri commented on gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/AbstractCertificateProvider.java
> +                    certificateKeys.add(new CertificateKey("ECSDA", toEcdsaString((ECPublicKey) publicKey)));
Can we create an entry into the CertificateFormat class ?

2022-04-05 07:25 UTC, leleueri commented on gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/AbstractCertificateProvider.java
> +        if (nimbusEcJwk.getCurve() != null) {
duplicate with line 249 ?

2022-04-05 08:44 UTC, farmborough commented on gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/AbstractCertificateProvider.java
> +        if (nimbusEcJwk.getCurve() != null) {
Oops.

2022-04-08 15:28 UTC, leleueri requested changes
I'm not able to use EC algorithm to generate default domain certificate (used when a domain is created)
https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml#L205

Tried with :
* ECDSA
* SHA256withECDSA

Maybe my values were wrong but as we generate RSA keys, I think we will have trouble anyway :thinking: 
https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java#L375
what is your thought

2022-04-08 15:35 UTC, farmborough commented
> I'm not able to use EC algorithm to generate default domain certificate (used when a domain is created) https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml#L205
> 
> Tried with :
> 
> * ECDSA
> * SHA256withECDSA
> 
> Maybe my values were wrong but as we generate RSA keys, I think we will have trouble anyway 🤔 https://github.com/gravitee-io/gravitee-access-management/blob/master/gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java#L375 what is your thought

Ah yes I think I can see the line in `CertificateServiceImpl` that needs changing (it's hardcoded to "RSA").

2022-04-25 12:49 UTC, leleueri approved these changes

2022-04-26 19:06 UTC, merged