Cicd/ee dockerfiles
gravitee-io/gravitee-access-management pull request #1762
Opened 2022-03-31 10:56 UTC by Hakim187

This PR is created in order to add the build and push workflow of v3 and v2 ee dockerfiles, that build and push the ee dockerfiles to the dockerhub repository, also all ee dockerfiles were now moved to this repo,

docker build test was launched using the orb, to build the am_v3 dockerfiles

CircleCI link : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-access-management/5829/workflows/dfe20a15-a9a6-4ffb-9558-c862be6747a2

this is the command to use to launch the build in dry-un on master branch : 

export CCI_TOKEN={CCI_TOKEN}
export ORG_NAME="gravitee-io"
export REPO_NAME="gravitee-access-management"
export BRANCH="master"
export GRAVITEEIO_VERSION="{version_to_build}"
export JSON_PAYLOAD="{
    \"branch\": \"${BRANCH}\",
    \"parameters\":
    {
        \"gio_product\": \"am_v3\",
        \"graviteeio_version\": \"${GRAVITEEIO_VERSION}\",
        \"dry_run\": true
    }
}"
curl -X GET -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Circle-Token: ${CCI_TOKEN}" https://circleci.com/api/v2/me | jq .
curl -X POST -d "${JSON_PAYLOAD}" -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Circle-Token: ${CCI_TOKEN}" https://circleci.com/api/v2/project/gh/${ORG_NAME}/${REPO_NAME}/pipeline | jq .

2022-04-05 14:37 UTC, remisultan requested changes

2022-04-05 14:37 UTC, remisultan commented on docker/enterprise/am/3.x/gateway/Dockerfile
> +FROM eclipse-temurin:11-jre-focal
```suggestion
FROM graviteeio/java:17
```

2022-04-05 14:37 UTC, remisultan commented on .circleci/config.yml
> +  gio_product:
⚠️ some of the config has been moved to https://github.com/gravitee-io/gravitee-access-management/blob/master/.circleci/workflows.yml

Make sure to rebase

2022-04-07 07:49 UTC, leleueri requested changes

2022-04-07 07:49 UTC, leleueri commented on .circleci/config.yml
> +  docker_build_and_push_am_v2:
We can remove v2 part. 
This version is not supported anymore

2022-04-07 07:49 UTC, leleueri commented on .circleci/config.yml
> +    enum: [am_v2, am_v3, none]
we can remove am_v2 as it is not supported anymore

2022-04-07 07:49 UTC, leleueri commented on docker/enterprise/am/2.x/gateway/Dockerfile
> +FROM alpine as builder
We can remove v2 dockerfile (v2 is not supported anymore)

2022-04-07 07:49 UTC, leleueri commented on docker/enterprise/am/2.x/management-api/Dockerfile
> +FROM alpine as builder
We can remove v2 dockerfile (v2 is not supported anymore)

2022-04-07 07:49 UTC, leleueri commented on docker/enterprise/am/2.x/management-ui/Dockerfile
> +ARG GRAVITEEIO_AM_VERSION=0
We can remove v2 dockerfile (v2 is not supported anymore)

2022-04-07 10:22 UTC, closed without merging

2022-04-07 10:22 UTC, Hakim187 commented
as this branch is not up to date, another PR was created : https://github.com/gravitee-io/gravitee-access-management/pull/1799