feat: required changes relate to HTTP resource
gravitee-io/gravitee-access-management pull request #1807
Opened 2022-04-12 08:31 UTC by ashraf706

fixes: https://github.com/gravitee-io/issues/issues/7517
Add template engine in factor context
Add factor context arguments as required
Implement error handler and template engine

2022-04-13 14:38 UTC, remisultan requested changes

2022-04-13 14:38 UTC, remisultan commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.html
> +          It supports AM Expression Language (EL) to configure the resource properties.
```suggestion
          It supports Gravitee Expression Language (EL) to configure the resource properties.
```

2022-04-13 14:38 UTC, remisultan commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.ts
> +  }
```suggestion
  isHttpResource() {
    if (this.resourceSchema) {
      const resourceId = this.resourceSchema.id;
      return resourceId ? resourceId.includes('HttpResourceConfiguration') : false;
    }
    return false;
  }
```

2022-04-14 09:13 UTC, farmborough commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.html
> +          This resource facilitates HTTP requests to send and verify verification code.
```suggestion
          This resource facilitates HTTP requests to send and verify a generated, one time code.
```

2022-04-14 09:13 UTC, farmborough commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.html
> +        <p>Response is accessible with EL such as: <br><b>&#123;'#xpath(#response.content, ".//code") == '1234'&#125;'</b><br> where code is a property of the XML response.</p>
```suggestion
        <p>The response can be accessed via EL using xpath, e.g.: <br><b>&#123;'#xpath(#response.content, ".//code") == '1234'&#125;'</b><br> where code is a property of the XML response.</p>
```

2022-04-14 09:13 UTC, farmborough commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.html
> +          User pin or verification code is available in <b>' &#123;#verificationCode &#125;'</b> EL property once user enters the code during the verify step.
```suggestion
          The user pin or verification code is available in the<b>' &#123;#verificationCode &#125;'</b> EL property after the user has submitted the code for verification.
```

2022-04-14 09:41 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
> +                .failureHandler(new MFAChallengeFailureHandler(authenticationFlowContextService));
done

2022-04-14 09:41 UTC, ashraf706 commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.html
> +          It supports AM Expression Language (EL) to configure the resource properties.
done

2022-04-14 09:41 UTC, ashraf706 commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.ts
> +  }
done

2022-04-14 09:42 UTC, ashraf706 commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.html
> +        <p>Response is accessible with EL such as: <br><b>&#123;'#xpath(#response.content, ".//code") == '1234'&#125;'</b><br> where code is a property of the XML response.</p>
done

2022-04-14 09:43 UTC, ashraf706 commented on gravitee-am-ui/src/app/domain/settings/resources/resource/resource.component.html
> +          User pin or verification code is available in <b>' &#123;#verificationCode &#125;'</b> EL property once user enters the code during the verify step.
done

2022-04-14 11:36 UTC, remisultan approved these changes
Usage is fine LGTM

I think the little note on the side regarding the `xpath` expression can be misleading.
There are single quotes here and there that do not make sense

<img width="371" alt="image" src="https://user-images.githubusercontent.com/8531515/163383045-0040e0af-cce2-4a42-8209-012a37fb665e.png">

2022-04-19 08:03 UTC, remisultan commented on pom.xml
> +        <gravitee-license-node.version>1.1.0</gravitee-license-node.version>
Why the license change here ?

2022-04-19 08:14 UTC, remisultan approved these changes

2022-04-19 08:14 UTC, remisultan commented on pom.xml
> +        <gravitee-license-node.version>1.1.0</gravitee-license-node.version>
seen with @ashraf706  already

2022-04-19 12:16 UTC, merged