[AM] - Swap classpath to allow Jaas to discover Kafka login module with SPI
gravitee-io/gravitee-access-management pull request #1840
Opened 2022-04-29 14:15 UTC by famaridon

I have no Github issue linked to this PR. But I have a zeendesk ticket [#4091](https://graviteesource.zendesk.com/hc/en-us/requests/4091)

2022-05-01 15:00 UTC, tcompiegne requested changes
Hey @famaridon ,

Can you target the 3.15.x branch and remove all files related to the ui (build.json, package-lock.json and package.json) ? 

That way we will fix all supported versions.

Thanks

2022-05-02 06:58 UTC, famaridon commented
I think it's good.

Thanks a lot.

2022-05-02 07:49 UTC, leleueri approved these changes

2022-05-02 09:51 UTC, merged

2022-05-02 09:52 UTC, leleueri commented
Thanks you for you contribution.