fix: update user data from IDP response
gravitee-io/gravitee-access-management pull request #1863
Opened 2022-05-17 10:38 UTC by farmborough

## :id:  
fixes gravitee-io/issues#7647

## :pencil2: A description of the changes proposed in the pull request
This fixes a bug where `UserService` was not parsing IDP responses for key fields such as email, username etc., and was only updating a user's additional properties. With this fix, a user profile will be updated whenever corresponding values are updated at the IDP.

2022-05-18 20:43 UTC, leleueri requested changes
In additon of the comment about the additionalInformation, I wondering if this PR is a duplicate of https://github.com/gravitee-io/issues/issues/7531

2022-05-18 20:43 UTC, leleueri commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
> -                    ((DefaultUser) user).setAdditionalInformation(additionalInformation);
removing this line may lead to regression as we test in line 256 if the additionalINformation is null. If so, we create a new HashMap but we do not set this map into the User object

2022-05-19 07:52 UTC, farmborough commented
> gravitee-io/issues#7531

I think it's a slightly different fix as this issue deals with updates originating from the IDP.

2022-05-20 07:48 UTC, leleueri commented
After discussing with @farmborough same issue as https://github.com/gravitee-io/issues/issues/7531.
As 7531 will be merge in 3.15.x we close this one.

2022-05-20 07:48 UTC, closed without merging

2022-05-20 07:50 UTC, farmborough commented
After chatting with @leleueri this does indeed appear to be a duplicate and is already fixed by https://github.com/gravitee-io/issues/issues/7531.