feat: display password when forgot password contains email
gravitee-io/gravitee-access-management pull request #1895
Opened 2022-06-03 11:38 UTC by remisultan

## :id: Reference related issue. 

https://github.com/gravitee-io/issues/issues/7796

## :pencil2: A description of the changes proposed in the pull request

This PR brings forgot password submission confirmation to display the email

## :memo: Test scenarios 

1. Activate forgot password
2. Initiate the login flow
3. Click to forgot password
4. Input the email of a known user
5. When confirmed your email should be display in the confirmation box

This is a nice example: https://github.com/gravitee-io/gravitee-access-management/pull/1822

2022-06-06 08:15 UTC, leleueri reviewed
If it is OK to pass the email as parameter LGTM, but let's ask to PO if it is ok.

2022-06-06 13:43 UTC, leleueri approved these changes

2022-06-06 14:29 UTC, tcompiegne requested changes
Still not sure about this solution ... 

I think we still have to discuss about it.

2022-06-10 12:01 UTC, tcompiegne approved these changes

2022-06-10 12:03 UTC, merged