feat(ui): intelligent adaptive access interface for MFA
gravitee-io/gravitee-access-management pull request #1897
Opened 2022-06-05 19:37 UTC by remisultan

## :id: Reference related issue. 

![adaptive-access](https://user-images.githubusercontent.com/8531515/172067563-047566bf-ac09-4880-af79-fe0b02e57a2c.gif)

https://github.com/gravitee-io/issues/issues/7689

## :pencil2: A description of the changes proposed in the pull request

This PR brings Adaptive Access new User Interface

## :memo: Test scenarios 

- Configure Adaptive Access and check if the behaviour is still consistent. 

⚠️ The Intelligent par can only be tested when the backend of Risk Assessment is merged

## :computer: Add screenshots for UI

Check the issue for UI screens

2022-06-06 17:05 UTC, leleueri requested changes
There is an error into the web console when the A-MFA with "Conditional' is selected

![image](https://user-images.githubusercontent.com/3110552/172209962-04ba76a6-803e-4762-bc29-064fb7f09224.png)

2022-06-07 11:44 UTC, remisultan commented on gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.ts
> +  styleUrls: ['./mfa-conditional.component.scss']
We keep so each component has it's associated scss file

2022-06-07 11:44 UTC, remisultan commented on gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts
> +    return MfaActivateComponent.modes.map(mode => MfaActivateComponent.modeOptions[mode]);
I indeed did the change in sub component but not here.
Will change it

2022-06-07 12:27 UTC, remisultan commented on gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.ts
> +  styleUrls: ['./mfa-conditional.component.scss']
FP

2022-06-16 07:09 UTC, remisultan commented
closed due to https://github.com/gravitee-io/gravitee-access-management/pull/1912

2022-06-16 07:09 UTC, closed without merging