Feat/risk assessment alerts
gravitee-io/gravitee-access-management pull request #1928
Opened 2022-06-23 11:12 UTC by farmborough

## :id: 
Fixes https://github.com/gravitee-io/issues/issues/7638

## :pencil2: 

Please disregards commit 8f385cb3ed26ba85f2e676511969f04c4cc444d4 as it has been cherry picked from @remisultan's corresponding [PR](feat/risk-assessment-feature).

Two main changes in this PR:

1. Additional Risk Assessment alert that can be enabled/disabled in the UI (see screenshot below)
2. New class in `RiskAssessmentHelper`, used by `AlertEventProcessor` for retrieving these configured values which are then used to compute the risk assessment at the risk assessment service.

## :memo: Test scenarios 

In the absence of the risk assessment service the most that can be manually tested is that enabling/disabling the risk assessment alert in AM leads to an alert trigger being created/removed in the Alert Engine. An instance of Alert Engine is therefore required as well as the AM plugin for connecting to Alert Engine.

## :computer: Add screenshots for UI

![Screenshot 2022-06-20 at 09 03 54](https://user-images.githubusercontent.com/99647292/174554768-7dd891fb-5cc3-4039-a906-cb053e181645.png)

2022-06-23 12:44 UTC, farmborough commented on pom.xml
> +        <gravitee-license-node.version>1.3.0-SNAPSHOT</gravitee-license-node.version>
Revert.

2022-06-27 07:17 UTC, leleueri requested changes

2022-06-27 07:17 UTC, leleueri commented on gravitee-am-ui/src/app/domain/alerts/general/general.component.ts
> +        description: ' Triggers a risk assessment',
Do we have to rename these labels using "Risk Based"

2022-06-27 07:53 UTC, remisultan commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
> +alerts:
Agreed

2022-06-28 10:25 UTC, leleueri reviewed
Don't succeed to make it works

2022-06-29 08:29 UTC, leleueri approved these changes

2022-06-29 08:30 UTC, merged