feat(theme): updated default language properties
gravitee-io/gravitee-access-management pull request #2075
Opened 2022-09-05 14:37 UTC by ashraf706

English and french language properties updated.
All the templates have been updated to incorporate the changes.

Github issue: https://github.com/gravitee-io/issues/issues/8054

2022-09-06 13:07 UTC, farmborough requested changes
I've taken the opportunity to fix the AM English syntax.

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_enroll.otp.description=Use and authenticator app to authenticate
```suggestion
mfa_enroll.otp.description=Use an authenticator app to authenticate
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_enroll.sms=We will send verification code to your phone number
```suggestion
mfa_enroll.sms=We will send a verification code to your phone number
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_enroll.email.description=Send email to your email address
```suggestion
mfa_enroll.email.description=Send an email to your email address
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_enroll.email=We will send verification code to your email address
```suggestion
mfa_enroll.email=We will send a verification code to your email address
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_enroll.http.description=Enter the code provided by the HTTP in next step
```suggestion
mfa_enroll.http.description=Enter the code provided by the HTTP in the next step
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_challenge.sms=Please type in the code sent by SMS on your mobile phone
```suggestion
mfa_challenge.sms=Please type in the code sent by SMS to your mobile phone
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_challenge.email=Please type in the code sent by Email
```suggestion
mfa_challenge.email=Please type in the code sent by email
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_challenge.alternate=Having trouble ? Try other methods
```suggestion
mfa_challenge.alternate=Having trouble? Try other methods
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_alternative.email=Send email to your email address
```suggestion
mfa_alternative.email=Send an email to your email address
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_alternative.http=Enter the code provided by the HTTP in next step
```suggestion
mfa_alternative.http=Enter the code provided by HTTP in next step
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_alternative.fido=Select 'Next' button to trigger the registration process
```suggestion
mfa_alternative.fido=Select the 'Next' button to trigger the registration process
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_recovery.description=Recovery codes are used to access your account when you cannot receive tow-factor authentication codes. Each code can only be used once.
```suggestion
mfa_recovery.description=Recovery codes are used to access your account when you cannot receive two-factor authentication codes. Each code can only be used once.
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +reset_password.error.description.label=Error description :
```suggestion
reset_password.error.description.label=Error description:
```

2022-09-06 13:07 UTC, farmborough commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
> +login.page.forgot.password=Mot de passe oubli� ?
```suggestion
login.page.forgot.password=Mot de passe oublié?
```

2022-09-08 08:08 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +login.page.forgot.password=Forgot Password ?
done

2022-09-08 08:08 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +forgot_password.error.description.label=Error description :
done

2022-09-08 08:08 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +registration.success.description=Thank you for creating account
done

2022-09-08 08:09 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +registration.error.description.label=Error description :
done

2022-09-08 08:09 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +password.exclude.user.info=Don't use your profile information in password
done

2022-09-08 08:09 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_alternative.http=Enter the code provided by the HTTP in next step
done

2022-09-08 08:09 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_alternative.fido=Select 'Next' button to trigger the registration process
done

2022-09-08 08:10 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +mfa_recovery.description=Recovery codes are used to access your account when you cannot receive tow-factor authentication codes. Each code can only be used once.
done

2022-09-08 08:10 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
> +reset_password.error.description.label=Error description :
done

2022-09-08 08:10 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
> +login.page.forgot.password=Mot de passe oubli� ?
done

2022-09-12 08:35 UTC, leleueri requested changes
In the WebAuthn login page, a span isn't translated :
![image](https://user-images.githubusercontent.com/3110552/189601538-00014626-2f3c-4e4e-8238-316dfdf2c14e.png)


**NOTE:** These translation need to be available into the manage api too (for preview mode)

2022-09-12 08:35 UTC, leleueri commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
> +mfa.email=Courriel
```suggestion
mfa.email=Courriel
```
I think it is ok to keep "email"

2022-09-12 08:35 UTC, leleueri commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
> +reset_password.error.description=Veuillez revenir � votre application client et r�essayer, ou contacter le propri�taire et demander de l'aide
```suggestion
reset_password.error.description=Veuillez revenir à votre application client et réessayer, ou contacter votre administrateur
```

2022-09-12 09:21 UTC, ashraf706 commented
> In the WebAuthn login page, a span isn't translated : ![image](https://user-images.githubusercontent.com/3110552/189601538-00014626-2f3c-4e4e-8238-316dfdf2c14e.png)
> 
> **NOTE:** These translation need to be available into the manage api too (for preview mode)

Updated the description with property

2022-09-12 12:34 UTC, leleueri requested changes
Two things:
* The form "registration_confirmation.html" has no entries into the en/fr properties files. (Change required)
* naming in the key are not consistent. for example, the `login` page keys start by "`login.page`" and the emails like `registration_confirmation` has keys that start by "`registration_confirmation.email`". For all new keys, `page` is missing from the key. Maybe it a convention we should put in place to make the distinction between keys that target a form and the one that target an email. I also wondering if the first element of the key should be the template name followed by the type (page or email) for example the mfa_challenge is a template name for both page and email (ex:  mfa_challenge.page.title / mfa_challenge.email.header.title) :thinking: wdyt ?

2022-09-12 14:59 UTC, ashraf706 commented
> 



> Two things:
> 
> * The form "registration_confirmation.html" has no entries into the en/fr properties files. (Change required)

**Done**

> * naming in the key are not consistent. for example, the `login` page keys start by "`login.page`" and the emails like `registration_confirmation` has keys that start by "`registration_confirmation.email`". For all new keys, `page` is missing from the key. Maybe it a convention we should put in place to make the distinction between keys that target a form and the one that target an email. I also wondering if the first element of the key should be the template name followed by the type (page or email) for example the mfa_challenge is a template name for both page and email (ex:  mfa_challenge.page.title / mfa_challenge.email.header.title) 🤔 wdyt ?

2022-09-13 19:54 UTC, leleueri approved these changes

2022-09-14 09:11 UTC, merged