feat(mfa): handle new type of MFA factors
gravitee-io/gravitee-access-management pull request #2090
Opened 2022-09-14 16:19 UTC by tcompiegne

closes gravitee-io/issues#8444

2022-09-16 13:22 UTC, leleueri approved these changes
I made some changes to make the plugin compatible with 3.15 and made some change into AM to manage resource filtering.

If these changes are OK  for you, you can merge :)

2022-09-20 19:10 UTC, leleueri requested changes
the enrollment & challenge screen is the one of the TOTP that ask for an authenticator app. Maybe we should adapt it ? wydt ?

2022-09-21 09:20 UTC, tcompiegne commented
For the time being we can keep like this.

2022-09-21 09:21 UTC, ashraf706 approved these changes

2022-09-22 09:00 UTC, leleueri approved these changes

2022-09-22 09:00 UTC, merged