fix: remove login_hint on backToIdentifierFirst action
gravitee-io/gravitee-access-management pull request #2098
Opened 2022-09-16 14:41 UTC by leleueri

fixes gravitee-io/issues#8236

## :id: Reference related issue.

2022-09-20 07:47 UTC, tcompiegne requested changes
why not change the link in the gateway ?

2022-09-20 14:21 UTC, leleueri commented
> why not change the link in the gateway ?

Your right, it should

2022-09-21 07:51 UTC, ashraf706 approved these changes

2022-09-21 09:42 UTC, tcompiegne approved these changes

2022-09-21 09:43 UTC, merged