AM-77-add-argon2id-support-to-am-
gravitee-io/gravitee-access-management pull request #2198
Opened 2022-10-24 14:36 UTC by farmborough

## :id: Reference related issue. 
Fixes [AM-77](https://graviteecommunity.atlassian.net/browse/AM-77)

## :pencil2: 

Adds Spring's Argon2 encrypter to AM and `PasswordHistoryService`.

2022-10-24 18:15 UTC, leleueri requested changes

2022-10-24 18:15 UTC, leleueri commented on gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/Argon2IdPasswordEncoder.java
> +    private final Argon2PasswordEncoder argon2PasswordEncoder = new Argon2PasswordEncoder();
IHMO, we should make the configuration the values for the Argon2PasswordEncoder to give some flexibilitty to the admin and set by default the [OWASP recommendation](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html).   

> Use [Argon2id](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#argon2id) with a minimum configuration of 15 MiB of memory, an iteration count of 2, and 1 degree of parallelism.

2022-10-25 13:06 UTC, farmborough commented
Will need to make sure the SCIM config also uses the Argon2 `PasswordEncoder`.

2022-10-28 14:34 UTC, leleueri reviewed
Looks good, for the encoder part.
Will approved this PR once the business logic one will be approved.

2022-11-04 08:01 UTC, leleueri approved these changes

2022-11-04 10:36 UTC, merged