Am 92 manually rotate key
gravitee-io/gravitee-access-management pull request #2217
Opened 2022-11-04 12:54 UTC by leleueri

2022-11-08 09:44 UTC, farmborough requested changes

2022-11-08 09:44 UTC, farmborough commented on gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java
> +    public static final String CERTIFICATE_SCHEMA_DEFINITION = "{\n" +
I think an actual json file kept in src/test/resources would be more maintainable than this.

2022-11-08 09:44 UTC, farmborough commented on gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java
> +        certOldest.setConfiguration("{\"content\":\"03c14ae4-5f9b-4636-814a-e45f9bb636c4.p12\",\"storepass\":\"gravitee\",\"alias\":\"default\",\"keypass\":\"gravitee\"}");
Again, hard coding json (or any other) syntax as a string leads to very hard to maintain code, even for tests. I would prefer to see these being read from resource files.

2022-11-08 09:44 UTC, farmborough commented on gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java
> +        certCustom.setConfiguration("{\"content\":\"03c14ae4-5f9b-4636-814a-e45f9bb636c4.p12\",\"storepass\":\"gravitee\",\"alias\":\"default\",\"keypass\":\"gravitee\"}");
Same here. If the certificate configuration ever needs to change, it will be difficult updating these.

2022-11-08 09:44 UTC, farmborough commented on gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts
> +    return (cert.status == 'renewed')
Typescript uses the same equality rules as Javascript, so it's generally best practice to use `===` over `==`. 

```suggestion
    return cert.status === 'renewed';
```

2022-11-08 09:44 UTC, farmborough commented on gravitee-am-test/specs/management/certificates.jest.spec.ts
> +            if (cert.status.toLowerCase() == 'renewed') {
```suggestion
            if (cert.status.toLowerCase() === 'renewed') {
```

2022-11-08 11:10 UTC, ashraf706 approved these changes

2022-11-08 15:06 UTC, farmborough approved these changes

2022-11-09 08:49 UTC, merged

2022-11-09 09:20 UTC, leleueri commented
Security Hotspot will be fixed by https://graviteecommunity.atlassian.net/browse/AM-141 
Code coveage isn't accurate as it doesn't take into account the Repository coverage