chore: Added ExitOnOutOfMemoryError JVM option as default into gravit…
gravitee-io/gravitee-access-management pull request #2387
Opened 2023-01-12 14:34 UTC by bozhidarstanishovski

In case of OOM sometimes the JVM (vertx) does not respond, while the liveness and readiness probes are working in Kubernetes. This is a problem because Kubernetes does not restart the pods in this case. 

A Java option "-XX:+ExitOnOutOfMemoryError" is added by default in the gravitee startup scripts. JVM exits on the first occurrence of an out-of-memory error.

2023-01-13 16:05 UTC, leleueri reviewed
Is it something we want to set in the startup script or an option into the Chart ?

2023-01-13 16:54 UTC, leleueri requested changes
With this change the user can't make a choise. The Exit will be executed on OOM whatever is the expectation of our user. IMHO, we should let the user take the decision by providing an option to simply enable or disable it.

I was expecting something like a new variable `GIO_JAVA_OPTS` that can be append to `JAVA_OPTS` and use the Chart to easily define the value of this `GIO_JAVA_OPTS`.

2023-01-23 09:08 UTC, bozhidarstanishovski commented
@leleueri I have changed the default behavior. New variable `GIO_EXIT_ON_OOM_ERROR` can be set to "true" if the user wants to append "-XX:+ExitOnOutOfMemoryError" to  `JAVA_OPTS`.

2023-01-23 09:38 UTC, leleueri approved these changes

2023-01-23 12:11 UTC, maikzumstrull commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/bin/gravitee
> +if [ "$GIO_EXIT_ON_OOM_ERROR" = "true" ]; then
I suggest flipping this logic, exiting on OOM unless this is explicitly set to false. Having the process hang around in an undefined state isn't useful. Defaults should be what's useful in most cases.

2023-02-24 08:06 UTC, leleueri commented on gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/bin/gravitee
> +
```suggestion
GIO_EXIT_ON_OOM_ERROR=${GIO_EXIT_ON_OOM_ERROR:-true}
if [ "$GIO_EXIT_ON_OOM_ERROR" = "true" ]; then
  JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError"
fi
```

2023-02-24 08:06 UTC, leleueri commented on gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/bin/gravitee
> +
```suggestion
GIO_EXIT_ON_OOM_ERROR=${GIO_EXIT_ON_OOM_ERROR:-true}
if [ "$GIO_EXIT_ON_OOM_ERROR" = "true" ]; then
  JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError"
fi
```

2023-03-02 13:57 UTC, closed without merging