AM-447-AM-IDP-When-using-an-internal-API-for-AM-no-validation-of-the-requests-payload-it-provided
gravitee-io/gravitee-access-management pull request #2459
Opened 2023-02-16 09:54 UTC by farmborough

## :id: 

Fixes [AM-447](https://gravitee.atlassian.net/browse/AM-447)

## :pencil2: 

Created a util class that checks JSON documents for negative values. 

## :memo: Test scenarios 

See the JIRA for an example IDP configuration that can be used to test this. Essentially, the steps to test are

1. Create an IDP (Suggest HTTP or In-memory as it's one of the easiest to configure)
2. Locate the IDP at the identities mongo table
3. Modify the 'configuration' field JSON to include invalid numeric values, e.g. ```"timeout" : -1000```

2023-02-22 10:39 UTC, mariano-fernandez requested changes

2023-02-22 10:39 UTC, mariano-fernandez commented on gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/utils/JsonNodeValidator.java
> +                    throw new IllegalArgumentException();
I would add a message to the exception to give some context

2023-02-23 08:17 UTC, remisultan commented on gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/utils/JsonNodeValidator.java
> +        idpConfig.elements().forEachRemaining(jsonNode -> {
Should we handle also when a field is required ?

2023-02-23 08:21 UTC, remisultan reviewed
The validity on the IDP configuration depends on the class defined on every IDP plugin.
Shouldn't we try to serialize it with the implementation of this configuration ?

2023-02-23 10:01 UTC, farmborough commented
> The validity on the IDP configuration depends on the class defined on every IDP plugin. Shouldn't we try to serialize it with the implementation of this configuration ?

I think what you're suggesting would be a much more thorough/better form of validation but I would argue it requires its own jira as an improvement, rather than this bug fix. I'm just validating on negative numbers but we could do with using regex or similar to provide more comprehensive validation, but that would be significantly more work.

2023-02-24 09:08 UTC, mariano-fernandez approved these changes

2023-02-28 13:45 UTC, merged

2023-02-28 13:46 UTC, farmborough commented
Sonarcloud wasn't detecting the junit 5 test so have bypassed the quality gate.