AM-385 delete login attempts username changed
gravitee-io/gravitee-access-management pull request #2467
Opened 2023-03-01 08:11 UTC by ashraf706

2023-03-01 10:34 UTC, aurelien-pacaud approved these changes
Tests OK & LGTM

2023-03-01 15:14 UTC, remisultan requested changes
One small concern here

2023-03-02 16:09 UTC, ashraf706 commented on gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
> +                            }
updated as suggested.

2023-03-03 15:24 UTC, remisultan approved these changes
LGTM

2023-03-06 08:43 UTC, merged