fix: template messages for phone call
gravitee-io/gravitee-access-management pull request #2476
Opened 2023-03-03 15:41 UTC by remisultan

## :id: Reference related issue. 

https://gravitee.atlassian.net/browse/AM-503

2023-03-07 09:09 UTC, remisultan commented on gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
> +mfa_alternative.call=Le code de v�rification vous sera transmis par appel t�l�phonique
Probably needs documentation

2023-03-07 11:02 UTC, ashraf706 requested changes

2023-03-07 11:02 UTC, ashraf706 commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge_alternatives.html
> +                <div th:if="${factor.factorType == 'SMS'}" class="radio-card">
There are another set of mfa_enroll and mfa_alternative files in gravitee-am-managemment-api-rest/**/resources folder. Those files are for rendering themes. 
You need to update those two files as well. Those files are duplicate, so you can copy and paste.

2023-03-07 14:03 UTC, ashraf706 approved these changes

2023-03-08 13:11 UTC, aurelien-pacaud approved these changes

2023-03-08 22:32 UTC, merged