feat: remember me option
gravitee-io/gravitee-access-management pull request #2871
Opened 2023-08-29 12:47 UTC by aurelien-pacaud

## :id: Reference related issue. 
https://gravitee.atlassian.net/browse/AM-744

## :pencil2: A description of the changes proposed in the pull request

If the user checks "remember me" during sign in a cookie is created to keep the user authenticated. Even if the session expired, if a valid remember cookie exists the user will be authenticated.

In production it's important to define a remember me duration greater than the session timeout.

## :memo: Test scenarios 

To be able to test and not wait 30 min it's important not persist session after closing the browser.

**Default sign in with configuration enabled at domain level**

- Create an application
- Register a user
- Enable the configuration to change the remember me duration at domain level (Settings -> User accounts)
- Choose a duration
- Disable persistent session (Application -> Settings -> Session management) 
- Sign in with the user with "remember me" checked
- Close your browser, the remember me cookie will be keep, the cookie session is removed
- Wait to let the remember me cookie expired
- Call again `oauth/authorize`
- The login form is displayed

**Default sign in with configuration enabled at application level**

- Create an application
- Register a user
- Enable the configuration to change the session duration at domain level (Your application -> Settings -> User accounts)
- Choose a duration
- Disable persistent session (Your application -> Settings -> Session management) 
- Sign in with the user with "remember me" checked
- Close your browser, the remember me cookie will be keep, the cookie session is removed
- Wait to let the remember me cookie expired
- Call again `oauth/authorize`
- The login form is displayed

**Webauth sign**

- Create an application
- Register a user
- Configure webauth at domain level
- Enable the configuration to change the session duration at domain or application level
- Choose a duration
- Click on 'Sign in with fingerprint, device or security key'
- Sign in with the user with "remember me" checked
- Close your browser, the remember me cookie is kept, the cookie session is removed
- Wait to let the remember me cookie expired
- Call again `oauth/authorize`
- The login form is displayed

**Identifier first**

- Create an application
- Register a user
- Configure 'identifier first'
- Enable the configuration to change the session duration at domain or application level
- Choose a duration
- Sign in with the user with "remember me" checked
- Close your browser, the remember me cookie will be keep, the cookie session is removed
- Wait to let the remember me cookie expired
- Call again `oauth/authorize`
- The login form is displayed

**Identifier first with social login**

- Create an application
- Register a user
- Configure 'identifier first'
- Enable the configuration to change the session duration at domain or application level
- Choose a duration
- Create a social IDP with Google for example
- Enable this IDP in your application
- Add a "Selection rule" to this IDP (username matching for example)
- Sign in with the user with "remember me" checked
- You will be automatically redirected to the IDP to authenticate the user
- Close your browser, the remember me cookie will be keep, the cookie session is removed
- Wait to let the remember me cookie expired
- Call again `oauth/authorize`
- The login form is displayed

## :computer: Add screenshots for UI

![Screenshot 2023-08-29 at 14 24 38](https://github.com/gravitee-io/gravitee-access-management/assets/3227290/d2ab103c-415e-45ef-8c6d-590ebdb6004e)
![Screenshot 2023-08-29 at 14 24 28](https://github.com/gravitee-io/gravitee-access-management/assets/3227290/c140999d-1f92-4798-b8b5-797eab679482)
![Screenshot 2023-08-29 at 14 24 12](https://github.com/gravitee-io/gravitee-access-management/assets/3227290/a1059a06-437b-4a71-9221-57cb859d0854)

2023-09-04 08:21 UTC, tcompiegne requested changes

2023-09-04 08:21 UTC, tcompiegne commented on gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_1_0/4.1.0-update-users-table-remember-me.yml
> +databaseChangeLog:
This file is not used anymore.

2023-09-04 08:21 UTC, tcompiegne commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
> +    private io.gravitee.am.service.UserService userService;
Not sure this service is used.

2023-09-04 08:21 UTC, tcompiegne commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
> +    private UserService managementuserService;
I think we can revert back to userService name.

2023-09-04 13:27 UTC, aurelien-pacaud commented on gravitee-am-model/src/main/java/io/gravitee/am/model/account/AccountSettings.java
> +
I just saw that but in the specification/figma it has to be configurable from "user accounts"

2023-09-05 19:39 UTC, tcompiegne approved these changes

2023-09-06 07:01 UTC, merged