fix: add sanitizeParametersEncoding toggle
gravitee-io/gravitee-access-management pull request #2885
Opened 2023-09-07 07:31 UTC by mariano-fernandez

## :id: Reference related issue. 

https://gravitee.atlassian.net/browse/AM-737

## :pencil2: A description of the changes proposed in the pull request

This PR introduces a hack 😞.

So far, when computing redirect URLs in AM, the `static` class `UriBuilderRequest` decodes and encodes all parameters.

When parameters aren't url-encoded, this is not a big deal. But when parameters are already url-encoded, we introduce a few issues.

Since the method is `UriBuilderRequest.resolveProxyRequest(...)` is used all around AM, it's hard to tell if removing the extra decoding will not break stuff.

This PR introduces the parameter `legacy.openid.sanitizeParametersEncoding` that, when set to `false`, disables the extra decoding.

For the future, we should remove the hack and any extra handling of parameters, only decoding parameters when they are received and encoding them when they leave AM Handlers.

## :memo: Test scenarios 

The issue contains a reproduction scenario.

I manually tested the fix in the following flows:
- Normal login flow
- Wrong password on normal login flow
- Login flow with `Identifier-first` enabled.
- Wrong password on ID first flow
- Navigation to Password reset page and back.
- Navigation to Register page and back.
- MFA with an SMS mock factor
- Wrong code with MFA mock factor.

## :books: Any other comments that will help with documentation

I'm not even sure where this should be documented

2023-09-08 07:38 UTC, passionne commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/StaticEnvironmentProvider.java
> +        return sanitizeParametersEncoding;
```suggestion
        if (sanitizeParametersEncoding == null) {
            sanitizeParametersEncoding = getEnvironmentProperty("legacy.openid.sanitizeParametersEncoding", boolean.class, true);
        }        
        return sanitizeParametersEncoding;
```

2023-09-08 07:41 UTC, passionne commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/utils/StaticEnvironmentProviderTest.java
> +    public void sanitizeParametersEncoding_environment_returns_value() {
```suggestion
    public void sanitizeParametersEncoding_environment_returns_cached_value() {
```

2023-09-08 08:56 UTC, passionne approved these changes
I added a few comments, but no blocker for me.
Thank you, it is a better way to handle this issue.

2023-09-11 09:08 UTC, leleueri requested changes
Code is OK but there is a regression when the legacy option is set to false for the use case describe here https://github.com/gravitee-io/issues/issues/7889.

![image](https://github.com/gravitee-io/gravitee-access-management/assets/3110552/730e4bbb-9a49-49c3-9c90-9e2e22ac57eb)

2023-09-11 13:40 UTC, mariano-fernandez commented
@leleueri good catch! I fixed that one and found another missing toggle. What a lovely plate of 🍝  😅 
Changes in a new commit. [`5aad56f` (#2885)](https://github.com/gravitee-io/gravitee-access-management/pull/2885/commits/5aad56f040fb427a8ee3da3438058ff7d003f823)

2023-09-13 08:46 UTC, mariano-fernandez commented
@leleueri I think you wanted to do some more testing. Any news regarding that? the sprint is arriving to an end and maybe is something we want to include in the scheduled release

2023-09-13 11:48 UTC, leleueri commented
> @leleueri I think you wanted to do some more testing. Any news regarding that? the sprint is arriving to an end and maybe is something we want to include in the scheduled release

Still have an issue

![image](https://github.com/gravitee-io/gravitee-access-management/assets/3110552/16b24bcc-343a-4989-81a4-f61d792a7d1c)

2023-09-18 07:27 UTC, leleueri approved these changes

2023-09-18 07:28 UTC, merged