fix: Evaluate the redirect_uri at each step of the auth flow
gravitee-io/gravitee-access-management pull request #3301
Opened 2023-12-15 10:44 UTC by leleueri

fixes AM-722

2023-12-15 11:50 UTC, mstasgravitee commented
There are filing tests in  AuthorizationEndpointTest and AuthorizationRequestParseParametersHandlerTest

2023-12-15 12:11 UTC, mstasgravitee requested changes

2023-12-15 12:11 UTC, mstasgravitee commented on gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
>  import io.gravitee.am.gateway.handler.root.resources.handler.client.ClientRequestParseHandler;
There are filing tests in AuthorizationEndpointTest and AuthorizationRequestParseParametersHandlerTest

2023-12-15 14:07 UTC, mstasgravitee approved these changes

2023-12-18 08:30 UTC, leleueri commented
Sonar says there is 0% of code coverage but There is some tests. Probably an issue with mixe of Junit 4 & 5.

2023-12-18 08:30 UTC, merged