AM-1116: added license log notifier
gravitee-io/gravitee-access-management pull request #3319
Opened 2023-12-18 12:39 UTC by ashraf706

### How to test

1. Change the cron expression for the certificate to `0 */1 * ? * *` to generate log per minute
2. Upload one expired and another about to expired certificate [please let me know if you need those certs]
3. Should be able to see AM console log entires such as below:

<img width="1529" alt="Screenshot 2023-12-18 at 12 35 20" src="https://github.com/gravitee-io/gravitee-access-management/assets/10583111/9cdfe226-cd91-4ead-a5e6-a58299bc7c4a">

4. There should be entry in the `notification_acknowledgements` collection for each certificate

2023-12-18 14:36 UTC, mstasgravitee requested changes

2023-12-18 14:36 UTC, mstasgravitee commented on gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/LogNotificationService.java
> +        if (expiredDate.getTime() < now.toEpochMilli()) {
```suggestion
        if (now.isAfter(expiredDate.toInstant())) {
```

2023-12-18 14:36 UTC, mstasgravitee commented on gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainNotifierServiceImpl.java
>  import static io.gravitee.am.management.service.impl.notifications.ManagementUINotifierConfiguration.CERTIFICATE_EXPIRY_TPL;
SonarCloud Code Analysis Failing after 16m — Quality Gate failed

2023-12-20 15:58 UTC, leleueri approved these changes

2023-12-20 15:58 UTC, leleueri commented on gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/LogNotificationService.java
> +        return future;
```suggestion
        return CompletableFuture.completedFuture(null);
```

2023-12-21 11:18 UTC, ashraf706 commented on gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainNotifierServiceImpl.java
>  import static io.gravitee.am.management.service.impl.notifications.ManagementUINotifierConfiguration.CERTIFICATE_EXPIRY_TPL;
Quality gate passed

2023-12-21 12:21 UTC, ashraf706 commented on gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/LogNotificationService.java
> +        return future;
done

2023-12-21 12:26 UTC, merged