Am 3318 fix gv exp lang quirks
gravitee-io/gravitee-access-management pull request #4326
Opened 2024-07-02 09:13 UTC by ThibaudAV

## :id: Reference related issue. 

AM-3318 

## :pencil2: A description of the changes proposed in the pull request

Revert this https://github.com/gravitee-io/gravitee-access-management/pull/4306 
and 
Use yarn instead of npm seam fix this issue. probably linked to depadance magic 🧙 

## :memo: Test scenarios 
💪 

📝 For local dev :
- Make sure you have updated node with `nvm use`
- If necessary, activate corpack with the command `corepack enable`
- (in unusual circumstances) if you already have a yarn installer with homebrew or similar, you may need to uninstall it and repeat the above steps.

## :computer: Add screenshots for UI

## :books: Any other comments that will help with documentation

## :man: :woman:@mentions of the person or team responsible for reviewing proposed changes

This is a nice example: https://github.com/gravitee-io/gravitee-access-management/pull/1822

2024-07-02 09:15 UTC, ThibaudAV commented on gravitee-am-ui/.yarn/releases/yarn-4.1.1.cjs
needed because https://github.com/eirslett/frontend-maven-plugin/issues/1032

2024-07-02 09:16 UTC, ThibaudAV commented on gravitee-am-ui/pom.xml
> +    <yarn.version>v1.22.22</yarn.version>
we use this version as a starter, it's normal then yarn uses the version 4

2024-07-02 09:17 UTC, ThibaudAV commented on gravitee-am-ui/package.json
> +    "@asciidoctor/core": "3.0.4",
added as requested by ui-component. i tried with npm too but it didn't change anything.

2024-07-02 12:05 UTC, lgw-gravitee approved these changes

2024-07-02 12:11 UTC, tcompiegne requested changes
@ThibaudAV is it possible to update the README of the UI console to describe how to build / run the project ?

Thanks

2024-07-02 12:35 UTC, ThibaudAV commented
@tcompiegne I've already updated it a bit
https://github.com/gravitee-io/gravitee-access-management/pull/4326/files#diff-ed75ef76bab0d813b7ea200140477a5ac26fe415bb9cc2128a8123eaae99edbe
but maybe you have a more precise idea? or you want me to netoire it because it's the default angular one

2024-07-03 13:09 UTC, tcompiegne approved these changes

2024-07-03 14:10 UTC, merged